name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov psutil

    - name: Run unit tests
      run: |
        pytest tests/ -v --cov=adaptive_classifier --cov-report=xml --cov-report=term -m "not integration"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  # Only run if unit tests pass
    timeout-minutes: 30  # Generous timeout for model downloads

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest psutil

    - name: Run integration tests
      run: |
        pytest tests/test_enterprise_classifiers_integration.py -v -m "integration" --tb=short

    - name: Integration test summary
      if: always()
      run: |
        echo "Integration tests completed. Check logs above for detailed results."